# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [4]:
# Create a 1-dimensional NumPy array using np.array()
d1 = np.array([1,2,3])
print(d1)
# Create a 2-dimensional NumPy array using np.array()
d2 = np.array([[2,3,4],
              [4,5,6]])
print(d2)
# Create a 3-dimensional Numpy array using np.array()
d3 = np.array([[[3,4,5,6],
               [4,5,6,7],
               [6,7,8,0]]])
print(d3)

[1 2 3]
[[2 3 4]
 [4 5 6]]
[[[3 4 5 6]
  [4 5 6 7]
  [6 7 8 0]]]


Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [14]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
print(f"shape of 1d array: {d1.shape}")
print(f"size of 1d array: {d1.size}")
print(f"dimension of 1d array: {d1.ndim}")
print(f"type of 1d array: {type(d1)}")
print(f"dtype of 1d array: {d1.dtype}")

shape of 1d array: (3,)
size of 1d array: 3
dimension of 1d array: 1
type of 1d array: <class 'numpy.ndarray'>
dtype of 1d array: int32


In [15]:
# Attributes of 2-dimensional array
print(f"shape of 2d array: {d2.shape}")
print(f"size of 2d array: {d2.size}")
print(f"dimension of 2d array: {d2.ndim}")
print(f"type of 2d array: {type(d2)}")
print(f"dtype of 2d array: {d2.dtype}")

shape of 2d array: (2, 3)
size of 2d array: 6
dimension of 2d array: 2
type of 2d array: <class 'numpy.ndarray'>
dtype of 2d array: int32


In [16]:
# Attributes of 3-dimensional array
print(f"shape of 3d array: {d3.shape}")
print(f"size of 3d array: {d3.size}")
print(f"dimension of 3d array: {d3.ndim}")
print(f"type of 3d array: {type(d3)}")
print(f"dtype of 3d array: {d3.dtype}")

shape of 3d array: (1, 3, 4)
size of 3d array: 12
dimension of 3d array: 3
type of 3d array: <class 'numpy.ndarray'>
dtype of 3d array: int32


In [19]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(d2)
df

0  1  2
0  2  3  4
1  4  5  6

In [22]:
# Create an array of shape (10, 2) with only ones
ones = np.ones(shape=(10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [23]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros(shape=(7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [31]:
# Create an array within a range of 0 and 100 with step 3
arr1 = np.arange(0,100,3)
arr1

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [34]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
arr2 = np.random.randint(10,size=(7,2))
arr2

array([[2, 4],
       [0, 9],
       [5, 2],
       [0, 6],
       [1, 0],
       [9, 1],
       [9, 8]])

In [40]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
arr3 = np.random.random(size=(3,5))
arr3

array([[0.82867889, 0.2693488 , 0.5656581 , 0.00184494, 0.08082573],
       [0.89880046, 0.89347606, 0.36863735, 0.05067288, 0.87454024],
       [0.99619802, 0.75284899, 0.99618104, 0.76961513, 0.7501549 ]])

In [43]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
arr4 = np.random.randint(10,size=(4,6))
arr4

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [46]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
arr5 = np.random.randint(10,size=(3,7))
arr5
# Find the unique numbers in the array you just created
np.unique(arr5)

array([0, 1, 2, 3, 4, 6, 7, 8, 9])

In [48]:
# Find the 0'th index of the latest array you created
arr5[0]

array([3, 7, 6, 8, 7, 4, 1])

In [49]:
# Get the first 2 rows of latest array you created
arr5[:2]

array([[3, 7, 6, 8, 7, 4, 1],
       [4, 7, 9, 8, 8, 0, 8]])

In [50]:
# Get the first 2 values of the first 2 rows of the latest array
arr5[:2,:2]

array([[3, 7],
       [4, 7]])

In [56]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
arr6 = np.random.randint(10,size=(3,5))
ones = np.ones((3,5))
arr6

array([[8, 3, 8, 2, 6],
       [5, 7, 8, 4, 0],
       [2, 9, 7, 5, 7]])

In [57]:
# Add the two arrays together
arr6 + ones

array([[ 9.,  4.,  9.,  3.,  7.],
       [ 6.,  8.,  9.,  5.,  1.],
       [ 3., 10.,  8.,  6.,  8.]])

In [58]:
# Create another array of ones of shape (5, 3)
ones = np.ones((5,3))

In [59]:
# Try add the array of ones and the other most recent array together
arr6 + ones

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [60]:
# Create another array of ones of shape (3, 5)
ones2 = np.ones((3,5))

In [61]:
# Subtract the new array of ones from the other most recent array
arr6 - ones2

array([[ 7.,  2.,  7.,  1.,  5.],
       [ 4.,  6.,  7.,  3., -1.],
       [ 1.,  8.,  6.,  4.,  6.]])

In [62]:
# Multiply the ones array with the latest array
arr6 * ones2

array([[8., 3., 8., 2., 6.],
       [5., 7., 8., 4., 0.],
       [2., 9., 7., 5., 7.]])

In [63]:
# Take the latest array to the power of 2 using '**'
arr6 ** 2

array([[64,  9, 64,  4, 36],
       [25, 49, 64, 16,  0],
       [ 4, 81, 49, 25, 49]], dtype=int32)

In [64]:
# Do the same thing with np.square()
np.square(arr6)

array([[64,  9, 64,  4, 36],
       [25, 49, 64, 16,  0],
       [ 4, 81, 49, 25, 49]], dtype=int32)

In [65]:
# Find the mean of the latest array using np.mean()
np.mean(arr6)

5.4

In [66]:
# Find the maximum of the latest array using np.max()
np.max(arr6)

9

In [67]:
# Find the minimum of the latest array using np.min()
np.min(arr6)

0

In [68]:
# Find the standard deviation of the latest array
np.std(arr6)

2.6025628394590847

In [69]:
# Find the variance of the latest array
np.var(arr6)

6.7733333333333325

In [71]:
# Reshape the latest array to (3, 5, 1)
arr6.reshape(3,5,1)
arr6.ndim

2

In [72]:
# Transpose the latest array
arr6.T

array([[8, 5, 2],
       [3, 7, 9],
       [8, 8, 7],
       [2, 4, 5],
       [6, 0, 7]])

What does the transpose do?

In [74]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
arr7 = np.random.randint(10,size=(3,3))
arr8 = np.random.randint(10,size=(3,2))

In [75]:
# Perform a dot product on the two newest arrays you created
arr7.dot(arr8)

array([[ 0, 53],
       [ 0, 63],
       [ 0, 31]])

In [77]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
arr9 = np.random.randint(10,size=(4,3))
arr10 = np.random.randint(10,size=(4,3))

In [78]:
# Perform a dot product on the two newest arrays you created
arr9.dot(arr10)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [79]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
arr9.dot(arr10.T)

array([[39, 32, 26, 31],
       [48, 42, 58, 26],
       [12,  5, 11, 15],
       [81, 53, 79, 74]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [90]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
ar1 = np.random.randint(10,size=(2,3))
ar2 = np.random.randint(10,size=(2,3))
print(ar1)
print(ar2)

[[5 2 8]
 [4 7 0]]
[[4 2 0]
 [3 4 6]]


In [91]:
# Compare the two arrays with '>'
ar1 > ar2

array([[ True, False,  True],
       [ True,  True, False]])

What happens when you compare the arrays with `>`?

In [92]:
# Compare the two arrays with '>='
ar1 >= ar2

array([[ True,  True,  True],
       [ True,  True, False]])

In [93]:
# Find which elements of the first array are greater than 7
ar1 > 7

array([[False, False,  True],
       [False, False, False]])

In [94]:
# Which parts of each array are equal? (try using '==')
ar1 == ar2

array([[False,  True, False],
       [False, False, False]])

In [95]:
# Sort one of the arrays you just created in ascending order
np.sort(ar1)

array([[2, 5, 8],
       [0, 4, 7]])

In [99]:
# Sort the indexes of one of the arrays you just created
np.argsort(ar1)

array([[1, 0, 2],
       [2, 0, 1]], dtype=int64)

In [100]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(ar1)

2

In [101]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(ar1)

5

In [103]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(ar1,1)

array([2, 1], dtype=int64)

In [105]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(ar1,0)

array([1, 0, 1], dtype=int64)

In [107]:
# Create an array of normally distributed random numbers
np.random.randn(2,3)

array([[-1.74906943, -1.3414035 , -1.62169462],
       [-1.14771997,  1.38960283, -0.85524052]])

In [114]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.random.randint(0,100,2)

array([39, 73])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.