In [2]:
import numpy as np

In [3]:
arr1 = np.array([2,3,1,3])
arr1

array([2, 3, 1, 3])

In [25]:
arr2 = np.array([[3,4,2,5],
                [2,5,2,5]])
arr2

array([[3, 4, 2, 5],
       [2, 5, 2, 5]])

In [24]:
arr3 = np.array([[[2,3,4,5,6],
                 [2,5,3,5,2],
                [6,5,3,5,3]],
                 [[2,3,16,7,8],
                 [2,3,4,1,7],
                 [3,4,8,9,6]]])
arr3

array([[[ 2,  3,  4,  5,  6],
        [ 2,  5,  3,  5,  2],
        [ 6,  5,  3,  5,  3]],

       [[ 2,  3, 16,  7,  8],
        [ 2,  3,  4,  1,  7],
        [ 3,  4,  8,  9,  6]]])

In [11]:
arr1.ndim,arr2.ndim,arr3.ndim

(1, 2, 3)

In [12]:
arr3.dtype

dtype('int32')

In [5]:
one = np.ones((3,4))
one

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
zeros = np.zeros((2,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
zeros.dtype

dtype('float64')

In [14]:
type(one)

numpy.ndarray

In [17]:
randomarr = np.random.randint(0,10,(3,5))
randomarr

array([[0, 6, 1, 1, 4],
       [2, 0, 5, 9, 1],
       [0, 0, 5, 2, 8]])

In [19]:
newrandom = np.random.random((3,5))
newrandom

array([[0.6993443 , 0.50304558, 0.78766456, 0.53249979, 0.76348228],
       [0.04989853, 0.23273037, 0.65004366, 0.2085525 , 0.52351228],
       [0.25052378, 0.72470221, 0.26753496, 0.26470735, 0.20290738]])

In [21]:
newrandom.dtype

dtype('float64')

In [29]:
np.unique(arr3)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 16])

In [35]:
print(arr1)
arr1[3]

[2 3 1 3]


3

In [37]:
arr3

array([[[ 2,  3,  4,  5,  6],
        [ 2,  5,  3,  5,  2],
        [ 6,  5,  3,  5,  3]],

       [[ 2,  3, 16,  7,  8],
        [ 2,  3,  4,  1,  7],
        [ 3,  4,  8,  9,  6]]])

In [61]:
arr3[:3,:1,:2]

array([[[2, 3]],

       [[2, 3]]])

In [65]:
newarray = np.random.randint(30,size=(2,3,3,4))
newarray

array([[[[ 3, 27, 20, 13],
         [25,  1, 16,  5],
         [ 5, 28, 13, 23]],

        [[24, 17, 26,  2],
         [28, 22, 24,  4],
         [ 5, 29, 25, 29]],

        [[10,  1, 13,  1],
         [ 5,  6, 23, 25],
         [ 6,  1,  5, 24]]],


       [[[ 9, 28, 15, 26],
         [26, 19, 29, 20],
         [18, 18, 13, 12]],

        [[15, 16, 12, 19],
         [ 7,  0, 24, 11],
         [26, 10, 14, 11]],

        [[10, 12, 29, 21],
         [22, 17,  1, 17],
         [ 9, 23, 26,  0]]]])

In [66]:
newarray.shape

(2, 3, 3, 4)

In [67]:
newarray.ndim

4

In [72]:
np.std(arr1)

0.82915619758885

In [73]:
np.var(arr1)

0.6875

In [74]:
np.var(arr2)

1.75

In [82]:
arr3.shape

(2, 3, 5)

In [80]:
arr2new.shape

(2, 4, 1)

In [84]:
arr3

array([[[ 2,  3,  4,  5,  6],
        [ 2,  5,  3,  5,  2],
        [ 6,  5,  3,  5,  3]],

       [[ 2,  3, 16,  7,  8],
        [ 2,  3,  4,  1,  7],
        [ 3,  4,  8,  9,  6]]])

In [85]:
arr3.T

array([[[ 2,  2],
        [ 2,  2],
        [ 6,  3]],

       [[ 3,  3],
        [ 5,  3],
        [ 5,  4]],

       [[ 4, 16],
        [ 3,  4],
        [ 3,  8]],

       [[ 5,  7],
        [ 5,  1],
        [ 5,  9]],

       [[ 6,  8],
        [ 2,  7],
        [ 3,  6]]])

In [93]:
mat1 = np.random.randint(10,size=(5,3))
mat2= np.random.randint(10,size=(5,3))

In [95]:
mat1

array([[6, 5, 1],
       [4, 4, 2],
       [8, 0, 7],
       [4, 5, 3],
       [2, 4, 0]])

In [97]:
mat2

array([[6, 4, 0],
       [9, 8, 0],
       [9, 1, 0],
       [1, 5, 3],
       [5, 3, 4]])

In [98]:
mat1 * mat2

array([[36, 20,  0],
       [36, 32,  0],
       [72,  0,  0],
       [ 4, 25,  9],
       [10, 12,  0]])

In [101]:
newmat = np.dot(mat2.T,mat1)

In [103]:
newmat.shape

(3, 3)

In [104]:
mat1.shape,mat2.shape

((5, 3), (5, 3))

In [105]:
mat1.T.shape

(3, 5)

In [4]:
import pandas as pd

In [25]:
np.random.seed(0)
pr = np.random.randint(20,size=(5,3))
pr

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [26]:
weekly_sales = pd.DataFrame(pr,index=['Monday','Tuesday','Wednesday','Thrusday','Friday'],
                           columns=['raptop','shuttle','tesla'])
weekly_sales

raptop  shuttle  tesla
Monday         12       15      0
Tuesday         3        3      7
Wednesday       9       19     18
Thrusday        4        6     12
Friday          1        6      7

In [28]:
prices = np.array([100,90,80])
prices.shape

(3,)

In [29]:
prices = pd.DataFrame(prices.reshape(1,3),index=['Price'],columns=['raptor','shuttle','tesla'])
prices

raptor  shuttle  tesla
Price     100       90     80

In [30]:
weekly_sales.shape,prices.shape

((5, 3), (1, 3))

In [47]:
total_sales = pr.dot(prices.T)

In [48]:
total_sales

array([[2550],
       [1130],
       [4050],
       [1900],
       [1200]])

In [50]:
weekly_sales.shape,pr.shape

((5, 3), (5, 3))

In [53]:
weekly_sales['total sales'] = total_sales

In [54]:
weekly_sales

raptop  shuttle  tesla  total sales
Monday         12       15      0         2550
Tuesday         3        3      7         1130
Wednesday       9       19     18         4050
Thrusday        4        6     12         1900
Friday          1        6      7         1200

In [61]:
a1 = np.array([9,2,8])
a2 = np.array([[2,3,4],
               [6,1,8]])

In [62]:
a1 > a2

array([[ True, False,  True],
       [ True,  True, False]])

In [64]:
newarray = np.random.randint(10,size=(3,5))
newarray

array([[8, 1, 3, 3, 3],
       [7, 0, 1, 9, 9],
       [0, 4, 7, 3, 2]])

In [66]:
np.sort(newarray,axis=0)

array([[0, 0, 1, 3, 2],
       [7, 1, 3, 3, 3],
       [8, 4, 7, 9, 9]])

In [67]:
np.argsort(newarray)

array([[1, 2, 3, 4, 0],
       [1, 2, 0, 3, 4],
       [0, 4, 3, 1, 2]], dtype=int64)